{"uuid": "6a6aa6b9-31de-4efe-bb05-a60261341cc5", "children": ["9ca91517-0fbe-4fa5-a0d9-78b1db1e287c"], "befores": [{"name": "login_page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=118.0.5993.89)\nStacktrace:\n\tGetHandleVerifier [0x00007FF72EE88EF2+54786]\n\t(No symbol) [0x00007FF72EDF5612]\n\t(No symbol) [0x00007FF72ECAA64B]\n\t(No symbol) [0x00007FF72EC8A9F5]\n\t(No symbol) [0x00007FF72ED10887]\n\t(No symbol) [0x00007FF72ED243CF]\n\t(No symbol) [0x00007FF72ED0BC43]\n\t(No symbol) [0x00007FF72ECE0941]\n\t(No symbol) [0x00007FF72ECE1B84]\n\tGetHandleVerifier [0x00007FF72F1D7F52+3524194]\n\tGetHandleVerifier [0x00007FF72F22D800+3874576]\n\tGetHandleVerifier [0x00007FF72F225D7F+3843215]\n\tGetHandleVerifier [0x00007FF72EF25086+694166]\n\t(No symbol) [0x00007FF72EE00A88]\n\t(No symbol) [0x00007FF72EDFCA94]\n\t(No symbol) [0x00007FF72EDFCBC2]\n\t(No symbol) [0x00007FF72EDECC83]\n\tBaseThreadInitThunk [0x00007FFE07837344+20]\n\tRtlUserThreadStart [0x00007FFE082426B1+33]\n\n", "trace": "  File \"C:\\Users\\PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\conftest.py\", line 39, in login_page\n    page.load()\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\pages\\login_page.py\", line 19, in load\n    self.browser.get(self.url)\n  File \"C:\\Users\\PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 353, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1698151339406, "stop": 1698151339410}], "start": 1698151339406, "stop": 1698151339531}