{"uuid": "4fcb4e7d-5398-458a-b30e-cce13a7e6442", "children": ["470772b5-172e-4965-9990-5e32b6a4e41a", "343d5250-c8c9-456e-8316-da1f6e2dbf15", "a7187b40-4b29-4edb-a3a4-d6f26f90508b", "b7e8c32d-c90f-49ab-b436-9f175be782ef", "200edcea-b477-436b-b1d7-1826c4653435", "6163ba3c-bb8e-40df-abd5-bd0f95e09e06", "42007e0d-aa3d-4bec-ba28-1df49b4ff1eb", "b7a29f8a-c9c9-44a7-8057-18dab350a202", "a6d08722-52a1-4642-b40b-e5d7b0c48b51", "c8025e6c-f99c-458a-80dc-b2a96a7ddde2", "aee1a580-931c-4f50-a3db-ed02aa68f230", "ba782c92-73f5-4889-bde0-299415327be4", "349a7ce9-7c51-43ec-be8e-747f4a9d5646", "81da98b1-2692-4d96-af8f-a70fa408d5f8", "77fbe747-d0de-488a-bfef-e1f0ae7e6ac9", "36c21199-67c5-4b2a-b628-f79aa8ee47b6", "d21d879f-55ec-4636-af7c-5dff1c2594b8"], "befores": [{"name": "browser", "status": "passed", "start": 1698152749384, "stop": 1698152751329}], "afters": [{"name": "browser::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=118.0.5993.89)\nStacktrace:\n\tGetHandleVerifier [0x00007FF708F48EF2+54786]\n\t(No symbol) [0x00007FF708EB5612]\n\t(No symbol) [0x00007FF708D6A64B]\n\t(No symbol) [0x00007FF708D4A9F5]\n\t(No symbol) [0x00007FF708DD0887]\n\t(No symbol) [0x00007FF708DE43CF]\n\t(No symbol) [0x00007FF708DCBC43]\n\t(No symbol) [0x00007FF708DA0941]\n\t(No symbol) [0x00007FF708DA1B84]\n\tGetHandleVerifier [0x00007FF709297F52+3524194]\n\tGetHandleVerifier [0x00007FF7092ED800+3874576]\n\tGetHandleVerifier [0x00007FF7092E5D7F+3843215]\n\tGetHandleVerifier [0x00007FF708FE5086+694166]\n\t(No symbol) [0x00007FF708EC0A88]\n\t(No symbol) [0x00007FF708EBCA94]\n\t(No symbol) [0x00007FF708EBCBC2]\n\t(No symbol) [0x00007FF708EACC83]\n\tBaseThreadInitThunk [0x00007FFE07837344+20]\n\tRtlUserThreadStart [0x00007FFE082426B1+33]\n\n", "trace": "  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 918, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\conftest.py\", line 23, in browser\n    driver.save_screenshot(os.path.join(screenshot_dir, screenshot_name))\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 917, in save_screenshot\n    return self.get_screenshot_as_file(filename)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 893, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 927, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 938, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1698152781173, "stop": 1698152781181}], "start": 1698152749384, "stop": 1698152781181}