{"uuid": "bfa003a4-ed55-46c5-84b3-cf11e22461ea", "children": ["edc26734-e8b2-43c7-a505-dd4095621665", "18470ef6-f3c5-49a1-9729-7ad38981af6e", "529488e7-2981-49ed-b4b4-bc59d8e4ff4b", "1edaf4c8-d062-4ef6-ad40-3ac438fef157", "bcc173d3-dcbc-4dba-b524-3890f65ff6f9", "74ff8f51-f93f-4e87-9d06-9c33f30e10eb", "8810671d-7320-48cf-8f71-9c44aa12f659", "2d7d40fb-7ab2-478b-950d-be1af38ae40b", "1667d923-6e8c-439f-86fc-a7f47156ef80", "d648c611-0251-4595-aed9-32ac002389d6", "0b44964d-b173-431d-9e9a-db2aafb2552b", "0859059a-b4ff-44f4-aa35-4a15fceb0035", "e97e0169-9037-46b5-bff1-9f66840bf5af", "b3ba7f05-ded2-4abd-8903-ada8969ad089", "7eb93f6a-c79e-4a37-907e-b7202b514a78", "b2fa269c-eecf-432f-9b78-fe1394568a94"], "befores": [{"name": "browser", "status": "passed", "start": 1698154312636, "stop": 1698154314716}], "afters": [{"name": "browser::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=118.0.5993.89)\nStacktrace:\n\tGetHandleVerifier [0x00007FF708F48EF2+54786]\n\t(No symbol) [0x00007FF708EB5612]\n\t(No symbol) [0x00007FF708D6A64B]\n\t(No symbol) [0x00007FF708D4A9F5]\n\t(No symbol) [0x00007FF708DD0887]\n\t(No symbol) [0x00007FF708DE43CF]\n\t(No symbol) [0x00007FF708DCBC43]\n\t(No symbol) [0x00007FF708DA0941]\n\t(No symbol) [0x00007FF708DA1B84]\n\tGetHandleVerifier [0x00007FF709297F52+3524194]\n\tGetHandleVerifier [0x00007FF7092ED800+3874576]\n\tGetHandleVerifier [0x00007FF7092E5D7F+3843215]\n\tGetHandleVerifier [0x00007FF708FE5086+694166]\n\t(No symbol) [0x00007FF708EC0A88]\n\t(No symbol) [0x00007FF708EBCA94]\n\t(No symbol) [0x00007FF708EBCBC2]\n\t(No symbol) [0x00007FF708EACC83]\n\tBaseThreadInitThunk [0x00007FFE07837344+20]\n\tRtlUserThreadStart [0x00007FFE082426B1+33]\n\n", "trace": "  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 918, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\conftest.py\", line 23, in browser\n    driver.save_screenshot(os.path.join(screenshot_dir, screenshot_name))\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 917, in save_screenshot\n    return self.get_screenshot_as_file(filename)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 893, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 927, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 938, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1698154334669, "stop": 1698154334676}], "start": 1698154312636, "stop": 1698154334676}