{"uuid": "d55339e9-2a8f-40f8-84e3-584ef7d4649c", "children": ["c41bb0d8-bbce-4d0b-82cf-ba60567a8028", "a24dbeef-4fbc-4821-af24-ac571310688d", "efd05cd9-c65f-4837-84f1-9ea2bcec32c1", "36cade72-985a-45b5-a8cd-348c956f1292", "770c5abd-a2f2-4c10-9ac5-aada0b288aaa", "b42688d1-aabe-4690-9e5d-f6f1a6390d00", "f2f4667b-e62a-46c2-bb6c-df1773572825", "44d8acda-cf92-4c85-8aac-2f0b06fbfaa2", "54594ea0-0b79-4eb1-9921-c2dbf1abcf1c", "6587af7c-9755-44a5-aed5-9b08fa4a3c63", "90695329-8c94-45aa-9ae3-b3508d06d147", "1691c7b9-5d87-4a94-83bc-25a37a3cddce", "b7e43085-4145-4df3-95c2-64b7063780ea", "a2de7e09-f5dc-4493-a39c-c57a9adee99b", "76df3b9b-2471-46d4-afbb-e43bb67159c5", "7a0d287b-18bb-4c17-acac-e09e2b29c0cb"], "befores": [{"name": "browser", "status": "passed", "start": 1698152654493, "stop": 1698152656253}], "afters": [{"name": "browser::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=118.0.5993.89)\nStacktrace:\n\tGetHandleVerifier [0x00007FF708F48EF2+54786]\n\t(No symbol) [0x00007FF708EB5612]\n\t(No symbol) [0x00007FF708D6A64B]\n\t(No symbol) [0x00007FF708D4A9F5]\n\t(No symbol) [0x00007FF708DD0887]\n\t(No symbol) [0x00007FF708DE43CF]\n\t(No symbol) [0x00007FF708DCBC43]\n\t(No symbol) [0x00007FF708DA0941]\n\t(No symbol) [0x00007FF708DA1B84]\n\tGetHandleVerifier [0x00007FF709297F52+3524194]\n\tGetHandleVerifier [0x00007FF7092ED800+3874576]\n\tGetHandleVerifier [0x00007FF7092E5D7F+3843215]\n\tGetHandleVerifier [0x00007FF708FE5086+694166]\n\t(No symbol) [0x00007FF708EC0A88]\n\t(No symbol) [0x00007FF708EBCA94]\n\t(No symbol) [0x00007FF708EBCBC2]\n\t(No symbol) [0x00007FF708EACC83]\n\tBaseThreadInitThunk [0x00007FFE07837344+20]\n\tRtlUserThreadStart [0x00007FFE082426B1+33]\n\n", "trace": "  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 918, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\conftest.py\", line 23, in browser\n    driver.save_screenshot(os.path.join(screenshot_dir, screenshot_name))\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 917, in save_screenshot\n    return self.get_screenshot_as_file(filename)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 893, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 927, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 938, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1698152674784, "stop": 1698152674791}], "start": 1698152654493, "stop": 1698152674791}