{"uuid": "75112666-b567-41ac-a539-d2d1f698b38b", "children": ["5d043827-20dc-4dd8-9963-0868d34e3c8c", "c3903eed-4832-4796-860e-fae2646bd8a0", "bc3e33fb-003a-44a1-99a1-a7c381468b7f", "d729b2b8-e0c8-48d2-9116-dace99845efb", "be01b27b-84f5-4f45-bb1a-e9f9c0d160b5", "a6dc307b-f88c-4a01-99ed-3b76d6338a74", "79c567f7-2c24-472c-af06-2ada5fe0008b", "8b97d62c-0e98-495f-a51d-0caf4edc833b", "418a3b80-7905-47d9-8b40-4029d07c8b5f", "dc7ac9ad-e2ab-45d1-825b-85ab26356a7b", "6c50ed09-f380-46ac-9f8d-a73eca8c438f", "6d5c3b64-fb62-4d6d-99ff-8421c5f1257d", "21a4f1d6-0bc5-4b98-a2bd-34eef950afec", "14e15dfd-2edb-4e6d-856d-74a15304ec18", "22423261-4e38-4eb3-9463-4b23483a3a8d", "67336c29-8cb1-47a5-8eb3-52d73d694fa3", "6ba68d4d-9057-428d-b149-908090009edf", "19b90359-fe37-4fb2-81bb-518b17f584bb", "33311dcc-1519-49c1-b5ee-b2b5ad7291c4", "342217ad-864b-49ef-b5b5-ce828ab4f437"], "befores": [{"name": "browser", "status": "passed", "start": 1698153198478, "stop": 1698153200275}], "afters": [{"name": "browser::0", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=61765): Max retries exceeded with url: /session/347272714c270208f069752c2ba5eaf5/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BFAE711130>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "trace": "  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 918, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\PC\\PycharmProjects\\teambook\\conftest.py\", line 23, in browser\n    driver.save_screenshot(os.path.join(screenshot_dir, screenshot_name))\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 917, in save_screenshot\n    return self.get_screenshot_as_file(filename)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 893, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 927, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 938, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\urllib3\\request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\urllib3\\request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 815, in urlopen\n    return self.urlopen(\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"C:\\Users\\PC\\PycharmProjects\\pythonProject\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1698153329051, "stop": 1698153345271}], "start": 1698153198478, "stop": 1698153345271}